import { StackProvider } from '@stackframe/stack';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages, setRequestLocale } from 'next-intl/server';
import { GoogleAdsenseScript } from '~/components/common/GoogleAdsenseScript';
import { ThemeProvider } from '~/components/theme/theme-provider';
import { Toaster } from '~/components/ui/toaster';
import { routing } from '~/i18n/routing';
import { stackServerApp } from '~/stack';

import '../globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ lang: locale }));
}

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  // getRequestConfig에서 이미 locale을 결정했으므로 getLocale() 사용
  const locale = await getLocale();
  setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleAdsenseScript />
        <StackProvider app={stackServerApp}>
          <NextIntlClientProvider messages={messages} locale={locale}>
            <ThemeProvider
              attribute='class'
              defaultTheme='light'
              enableSystem
              disableTransitionOnChange
            >
              <div className='mx-auto h-full max-w-3xl bg-[#872cff03] px-4'>
                {children}
              </div>
              <Toaster />
            </ThemeProvider>
          </NextIntlClientProvider>
        </StackProvider>
      </body>
    </html>
  );
}
