import { StackProvider } from '@stackframe/stack';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import ProfileHeader from '~/components/common/Header/ProfileHeader';
import { ThemeProvider } from '~/components/theme/theme-provider';
import { Toaster } from '~/components/ui/toaster';
import { stackServerApp } from '~/stack';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StackProvider app={stackServerApp}>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem
            disableTransitionOnChange
          >
            <div className='mx-auto h-full max-w-3xl bg-[#872cff03] px-4'>
              <ProfileHeader />
              {children}
            </div>
            <Toaster />
          </ThemeProvider>
        </StackProvider>
      </body>
    </html>
  );
}
